version: '3.9'
services:
  db:
    image: mysql:5.7
    container_name: my_db
    restart: always
    environment:
      - MYSQL_DATABASE=my_db
      - MYSQL_ROOT_PASSWORD=rootpass
    volumes:
      - "./my_db.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - '3306:3306'
    networks:
      - local_keycloak_network

  xepelin-bank:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xepelin-bank
    depends_on:
      - db
    restart: always
    environment:
      - TOKEN=my-secret-token
      - HOST=localhost:8080
      - DB_USER=root
      - DB_PASS=rootpass
      - DB_HOST=db
      - DB_PORT=3306
    ports:
      - '8080:8080'
    expose:
      - 8080
    networks:
      - local_keycloak_network

networks:
  local_keycloak_network:
